sudo: required

services:
  - docker

langauge: go

go:
  - 1.13.x
  - 1.14.x

script:
  - make format-check
  - make build
  - make test
  - make docker

branches:
  only:
    - master
    - docker-travis-builds  #TODO delete