version: "3.4"
services:
  rabbitmq:
    container_name: rabbitmq-pubsub-adapter-dev
    image: rabbitmq:3.8.2-management
    ports:
      - "6369:4369"
      - "46672:25672"
      - "7671-7672:5671-5672"
      - "17671-17672:15671-15672"
      - "17692:15692"
    volumes:
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./rabbitmq/definitions.json:/opt/definitions.json:ro

  pubsub-emulator:
    container_name: pubsub-emulator-pubsub-adapter-dev
    image: bigtruedata/gcloud-pubsub-emulator
    ports:
      - "8539:8539"
    command: start --host-port 0.0.0.0:8539

  pubsub-adapter:
    container_name: pubsub-adapter-dev
    image: eu.gcr.io/census-rm-ci/census-rm-pubsub-adapter
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub-emulator-pubsub-adapter-dev:8539
      - RABBIT_CONNECTION=amqp://guest:guest@rabbitmq-pubsub-adapter-dev:5672/
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
      - RABBIT_HOST=rabbitmq-pubsub-adapter-dev
      - RABBIT_PORT=5672
      - RABBIT_VHOST=/
      - EQ_RECEIPT_PROJECT=project
      - OFFLINE_RECEIPT_PROJECT=offline-project
    restart: on-failure
